on:
  push:

name: ci

jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
    - uses: docker-practice/actions-setup-docker@1.0.2
      with:
        docker_version: "20.10"
        docker_channel: test
    - run: |
        {
          echo "FROM alpine"
          echo "RUN echo 1"
        } | tee Dockerfile
    - uses: azure/docker-login@v1
      with:
        login-server: ghcr.io
        username: khs1994
        password: ${{ secrets.GHCR_IO_TOKEN }}
    - uses: azure/docker-login@v1
      with:
        login-server: pcit-docker.pkg.coding.net
        username: khs1994-1601432822176
        password: ${{ secrets.CODING_DOCKER_PASSWORD }}
    - uses: azure/docker-login@v1
      with:
        login-server: registry.baidubce.com
        username: 29bda121d7644a6e8d0294aa33840882
        password: ${{ secrets.BAIDU_DOCKER_PASSWORD }}
    - uses: azure/docker-login@v1
      with:
        login-server: registry.us-east-1.aliyuncs.com
        username: 906210846@qq.com
        password: ${{ secrets.DOCKER_PASSWORD }}
    - uses: azure/docker-login@v1
      with:
        login-server: uswccr.ccs.tencentyun.com
        username: 906210846
        password: ${{ secrets.DOCKER_PASSWORD }}
    - uses: azure/docker-login@v1
      with:
        # login-server: 
        username: khs1994
        password: ${{ secrets.DOCKER_PASSWORD }}
    - run: |
          for item in $registrys;
          do
            echo ::group::Test $item
            docker buildx build \
            --cache-to=${item}/khs1994/alpine:cache \
            . && echo "::warning:: [ $item ] allow cache upload" || echo "::error:: [ $item ] not allow cache upload"
            echo ::endgroup::
          done
      name: Test
      env:
        registrys: >-
          registry.baidubce.com
          registry.us-east-1.aliyuncs.com
          uswccr.ccs.tencentyun.com
          pcit-docker.pkg.coding.net/khs1994-docker
          ghcr.io
          docker.io
